### ISSUE TITLE
PyPI release / package clash

### ISSUE THREAD

**Issue by jayvdb** [AICoE/ludus#11]
https://pypi.org/project/ludus/ is already taken on PyPI, and it uses `ludus` in the site packages.

It would be a good idea to find and reserve a name on PyPI, and adjust the project structure to be suitable for releasing on PyPI, which then helps for distros and distro-centric sites wanting to re-packaging it and deploy them.

**Comment by goern** [comment]
@durandom it seems to be a good idea to rename the project, if we want to publish modules on pypi....

**Comment by durandom** [comment]
meh, any ideas / suggestions?

cyborg-regidores ?

**Comment by jayvdb** [comment]
/remove-lifecycle stale

@sesheta , there is only one issue in this repo, and it isnt the type of issue that goes stale.  I dont see how a stale bot is helpful in this repo.
